#You declare each potion under a title (it doesn't matter what title)
potion1:
  #Required items in the player's inventory
  criteria:
    - DIRT
    - DIAMOND_HOE
  #Required armor being worn.
  #Put Wool for a non-armor helmet [ONLY WORKS ON HELMETS, will always check helmet reguardless of field] (such as wool or dirt on your head)
  #AIR for nothing, and Ignore to ignore
  
  #Currently ignore does not seem to work (known bug)
  
  armor:
    helmet: DIAMOND_HELMET
    chestplate: DIAMOND_CHESTPLATE
    leggings: DIAMOND_LEGGINGS
    boots: GOLD_BOOTS
  #Effects to give
  effects:
    #List effects like this:
    #POTIONEFFECTNAME::LEVEL
    - REGENERATION::3
    - DAMAGE_RESISTANCE::1
#Sample number 2
diamondpotion:
  criteria:
    - DIAMOND_BLOCK
  armor:
    helmet: Ignore
    chestplate: CHAINMAIL_CHESTPLATE
    leggings: Ignore
    boots: IRON_BOOTS
  effects:
    - SLOW::4
    - REGENERATION::1