#You declare each potion under a title (it doesn't matter what title)
potion1:
  #Required items in the player's inventory
  criteria:
    - DIRT
  #Required armor being worn.
  #Put Wool for a non-armor helmet [ONLY WORKS ON HELMETS, will always check helmet reguardless of field] (such as wool or dirt on your head)
  #AIR for nothing, and Ignore to ignore
  armor:
    helmet: DIAMOND_HELMET
    chestplate: DIAMOND_CHESTPLATE
    leggings: DIAMOND_LEGGINGS
    boots: GOLD_BOOTS
  #Effects to give
  effects:
    #List effects like this:
    #POTIONEFFECTNAME::LEVEL
    - REGENERATION::1
#Sample number 2
diamondpotion:
  criteria:
    - DIAMOND_BLOCK
  armor:
    helmet: Ignore
    chestplate: Ignore
    leggings: Ignore
    boots: Ignore
  effects:
    - SLOWNESS::4
    - REGENERATION::2