#You declare each potion under a title (it doesn't matter what title)
potion1:
  #The ignore property, so don't touch if you DON'T want to use potion1, but DO REMOVE if you DO want to use potion1
  #Workaround for the fact that the default config is used: delete the line below if you DO want to use this potion
  ignore: true
  
  
  
  # Item in hand, do not define if you do not want an item in hand
  
  # handitem: DO_NOT_USE
  
  #Required items in the player's inventory (don't define if you don't have any)
  criteria:
    - DIRT
    - DIAMOND_HOE
    
  #Items that CAN'T be in a players inventory for the potion effect to work
  #Just leave alone 
  blacklist:
    - GOLD_SWORD #So no butter swords
    - DIAMOND_AXE #Or diamond axes if you want regeneration 3 and resistance 1
    
  #Required armor being worn.
  #Put Wool for a non-armor helmet [ONLY WORKS ON HELMETS, will always check helmet reguardless of field] (such as wool or dirt on your head)
  #AIR for nothing, and Ignore to ignore
  armor:
    helmet: DIAMOND_HELMET
    chestplate: DIAMOND_CHESTPLATE
    leggings: DIAMOND_LEGGINGS
    boots: GOLD_BOOTS
  #Effects to give
  effects:
    #List effects like this:
    #POTIONEFFECTNAME::LEVEL
    - REGENERATION::3
    - DAMAGE_RESISTANCE::1
#Sample number 2
diamondpotion:
  #The ignore property, so don't touch if you DON'T want to use diamondpotion, but DO REMOVE if you DO want to use diamondpotion
  #Workaround for the fact that the default config is used: delete the line below if you DO want to use this potion
  ignore: true
  
  #I'm checking the item in hand
  handitem: DIAMOND_SWORD
  #Since I don't have criteria (except armor), I don't need a criteria place
  #Or a blacklist, so no item invalidates the potion
  
  armor:
    helmet: Ignore
    chestplate: CHAINMAIL_CHESTPLATE
    leggings: Ignore
    boots: IRON_BOOTS
  effects:
    - SLOW::4
    - REGENERATION::1
