name: InventoryPotionEffectModifier
main: com.glen3b.plugin.invpotions.InventoryPotionEffects
version: 1.5
commands:
   matchinv:
      description: Match a specific inventory requirement for a potion
      usage: /matchinv <name of requirement> [player]
      permission: invpotions.matchinv
      permission-message: You cannot match your inventory to a potion effect requirement because you don't have invpotions.matchinv
   invpotions:
      description: Administer Inventory-Based Potions (do tasks such as reloading)
      usage: /invpotions <reload>
      permission: invpotions.administer
      permission-message: You cannot administer Inventory-Based Potions
permissions:
    invpotions.commands:
        description: Gives access to all inventory-based potion commands
        children:
            invpotions.administer: true
            invpotions.matchinv: true
    invpotions.administer:
        description: Allows you to reload the config
        default: op
    invpotions.matchinv:
        description: Allows you to match an inventory requirement for a potion
        default: op
    invpotions.bypass:
        description: Allows you to bypass potion effects
        default: false
    invpotions.potion.*:
        description: Allow all potion effects
        default: true